name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    # Устанавливаем Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Установка зависимостей
    - name: Install dependencies
      run: npm ci

    # Установка Playwright с зависимостями
    - name: Install Playwright
      run: npx playwright install --with-deps

  # Запуск тестов Playwright с генерацией отчёта Allure
    - name: Run Playwright tests with Allure
      run: npx playwright test --reporter=line,allure-playwright
      continue-on-error: true 

    # Генерация отчета Allure
    - name: Generate Allure Report
      if: always()
      run: npm run allure-report


    - name: Check Playwright test-results
      run: ls -la ./test-results
    
    - name: Check Allure results
      run: ls -la ./allure-results

    - name: Check Allure report
      run: ls -la ./allure-report

    # Загружаем результаты тестов Playwright как артефакты
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-test-results
        path: ./test-results

    # Загружаем результаты отчета Allure как артефакты
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-test-results
        path: ./allure-report

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report
        disable_nojekyll: true